package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * AnswerOptionEntity generated by hbm2java
 */
public class AnswerOptionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1005970152725681621L;
	
	private Long optionId;
	private Long questionId;
	private String optionText;
	private Byte iscorrect;

	public AnswerOptionEntity() {
	}

	public AnswerOptionEntity(Long questionId, String optionText) {
		this.questionId = questionId;
		this.optionText = optionText;
	}

	public AnswerOptionEntity(Long questionId, String optionText, Byte iscorrect) {
		this.questionId = questionId;
		this.optionText = optionText;
		this.iscorrect = iscorrect;
	}

	public Long getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Long optionId) {
		this.optionId = optionId;
	}

	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	public String getOptionText() {
		return this.optionText;
	}

	public void setOptionText(String optionText) {
		this.optionText = optionText;
	}

	public Byte getIscorrect() {
		return this.iscorrect;
	}

	public void setIscorrect(Byte iscorrect) {
		this.iscorrect = iscorrect;
	}

}
