package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 10:39:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AnswerOptionMediaEntity generated by hbm2java
 */
@Entity
@Table(name = "ANSWER_OPTION_MEDIA", catalog = "qme")
public class AnswerOptionMediaEntity implements java.io.Serializable {

	private static final long serialVersionUID = 5792900660188386851L;
	
	private Long optionMediaId;
	private Long optionId;
	private Integer optionMediaType;
	private byte[] optionMedia;

	public AnswerOptionMediaEntity() {
	}

	public AnswerOptionMediaEntity(Long optionId, Integer optionMediaType) {
		this.optionId = optionId;
		this.optionMediaType = optionMediaType;
	}

	public AnswerOptionMediaEntity(Long optionId, Integer optionMediaType,
			byte[] optionMedia) {
		this.optionId = optionId;
		this.optionMediaType = optionMediaType;
		this.optionMedia = optionMedia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OPTION_MEDIA_ID", unique = true, nullable = false)
	public Long getOptionMediaId() {
		return this.optionMediaId;
	}

	public void setOptionMediaId(Long optionMediaId) {
		this.optionMediaId = optionMediaId;
	}

	@Column(name = "OPTION_ID", nullable = false)
	public Long getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Long optionId) {
		this.optionId = optionId;
	}

	@Column(name = "MEDIA_TYPE_ID", nullable = false, length = 50)
	public Integer getOptionMediaType() {
		return this.optionMediaType;
	}

	public void setOptionMediaType(Integer optionMediaType) {
		this.optionMediaType = optionMediaType;
	}

	@Column(name = "OPTION_MEDIA")
	public byte[] getOptionMedia() {
		return this.optionMedia;
	}

	public void setOptionMedia(byte[] optionMedia) {
		this.optionMedia = optionMedia;
	}

}
