package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AnswerOptionEntity generated by hbm2java
 */
@Entity
@Table(name = "ANSWER_OPTION", catalog = "qme")
public class AnswerOptionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1005970152725681621L;
	
	private Long optionId;
	private Long questionId;
	private String optionText;
	private Byte iscorrect;

	public AnswerOptionEntity() {
	}

	public AnswerOptionEntity(Long questionId, String optionText) {
		this.questionId = questionId;
		this.optionText = optionText;
	}

	public AnswerOptionEntity(Long questionId, String optionText, Byte iscorrect) {
		this.questionId = questionId;
		this.optionText = optionText;
		this.iscorrect = iscorrect;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OPTION_ID", unique = true, nullable = false)
	public Long getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Long optionId) {
		this.optionId = optionId;
	}

	@Column(name = "QUESTION_ID", nullable = false)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@Column(name = "OPTION_TEXT", nullable = false, length = 65535)
	public String getOptionText() {
		return this.optionText;
	}

	public void setOptionText(String optionText) {
		this.optionText = optionText;
	}

	@Column(name = "ISCORRECT")
	public Byte getIscorrect() {
		return this.iscorrect;
	}

	public void setIscorrect(Byte iscorrect) {
		this.iscorrect = iscorrect;
	}

}
