package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * AnswerReferenceMediaEntity generated by hbm2java
 */
public class AnswerReferenceMediaEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7353838286698930968L;
	
	private Long answerRefMediaId;
	private Long questionId;
	private String refMediaType;
	private byte[] refMedia;

	public AnswerReferenceMediaEntity() {
	}

	public AnswerReferenceMediaEntity(Long questionId, String refMediaType) {
		this.questionId = questionId;
		this.refMediaType = refMediaType;
	}

	public AnswerReferenceMediaEntity(Long questionId, String refMediaType,
			byte[] refMedia) {
		this.questionId = questionId;
		this.refMediaType = refMediaType;
		this.refMedia = refMedia;
	}

	public Long getAnswerRefMediaId() {
		return this.answerRefMediaId;
	}

	public void setAnswerRefMediaId(Long answerRefMediaId) {
		this.answerRefMediaId = answerRefMediaId;
	}

	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	public String getRefMediaType() {
		return this.refMediaType;
	}

	public void setRefMediaType(String refMediaType) {
		this.refMediaType = refMediaType;
	}

	public byte[] getRefMedia() {
		return this.refMedia;
	}

	public void setRefMedia(byte[] refMedia) {
		this.refMedia = refMedia;
	}

}
