/**
 * Name      : com.malcolm.qme.springdata.entity.AnswerOptionEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : Answer Option Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AnswerOptionEntity generated by hbm2java
 */
@Entity
@Table(name = "ANSWER_OPTION", catalog = "qme")
public class AnswerOptionEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7816994725559572572L;
	
	private Integer optionId;
	private int questionId;
	private String optionText;
	private Byte iscorrect;

	public AnswerOptionEntity() {
	}

	public AnswerOptionEntity(int questionId, String optionText) {
		this.questionId = questionId;
		this.optionText = optionText;
	}

	public AnswerOptionEntity(int questionId, String optionText, Byte iscorrect) {
		this.questionId = questionId;
		this.optionText = optionText;
		this.iscorrect = iscorrect;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OPTION_ID", unique = true, nullable = false)
	public Integer getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Integer optionId) {
		this.optionId = optionId;
	}

	@Column(name = "QUESTION_ID", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "OPTION_TEXT", nullable = false, length = 65535)
	public String getOptionText() {
		return this.optionText;
	}

	public void setOptionText(String optionText) {
		this.optionText = optionText;
	}

	@Column(name = "ISCORRECT")
	public Byte getIscorrect() {
		return this.iscorrect;
	}

	public void setIscorrect(Byte iscorrect) {
		this.iscorrect = iscorrect;
	}

}
