/**
 * Name      : com.malcolm.qme.springdata.entity.AnswerReferenceMediaEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : Answer Reference Media Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AnswerReferenceMediaEntity generated by hbm2java
 */
@Entity
@Table(name = "ANSWER_REFERENCE_MEDIA", catalog = "qme")
public class AnswerReferenceMediaEntity implements java.io.Serializable {

	private static final long serialVersionUID = 5542631772390685116L;
	
	private Integer answerRefMediaId;
	private int questionId;
	private String refMediaType;
	private byte[] refMedia;

	public AnswerReferenceMediaEntity() {
	}

	public AnswerReferenceMediaEntity(int questionId, String refMediaType) {
		this.questionId = questionId;
		this.refMediaType = refMediaType;
	}

	public AnswerReferenceMediaEntity(int questionId, String refMediaType,
									  byte[] refMedia) {
		this.questionId = questionId;
		this.refMediaType = refMediaType;
		this.refMedia = refMedia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ANSWER_REF_MEDIA_ID", unique = true, nullable = false)
	public Integer getAnswerRefMediaId() {
		return this.answerRefMediaId;
	}

	public void setAnswerRefMediaId(Integer answerRefMediaId) {
		this.answerRefMediaId = answerRefMediaId;
	}

	@Column(name = "QUESTION_ID", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "REF_MEDIA_TYPE", nullable = false, length = 50)
	public String getRefMediaType() {
		return this.refMediaType;
	}

	public void setRefMediaType(String refMediaType) {
		this.refMediaType = refMediaType;
	}

	@Column(name = "REF_MEDIA")
	public byte[] getRefMedia() {
		return this.refMedia;
	}

	public void setRefMedia(byte[] refMedia) {
		this.refMedia = refMedia;
	}

}
