package com.malcolm.qme.springdata.entity;

// Generated May 16, 2015 7:28:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AnswerOptionMediaEntity generated by hbm2java
 */
@Entity
@Table(name = "ANSWER_OPTION_MEDIA", catalog = "qme")
public class AnswerOptionMediaEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7762543847542101433L;

	private Long optionMediaId;
	private Long optionId;
	private Integer mediaTypeId;
	private byte[] optionMedia;

	public AnswerOptionMediaEntity() {
	}

	public AnswerOptionMediaEntity(Long optionId, Integer mediaTypeId,
			byte[] optionMedia) {
		this.optionId = optionId;
		this.mediaTypeId = mediaTypeId;
		this.optionMedia = optionMedia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OPTION_MEDIA_ID", unique = true, nullable = false)
	public Long getOptionMediaId() {
		return this.optionMediaId;
	}

	public void setOptionMediaId(Long optionMediaId) {
		this.optionMediaId = optionMediaId;
	}

	@Column(name = "OPTION_ID", nullable = false)
	public Long getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Long optionId) {
		this.optionId = optionId;
	}

	@Column(name = "MEDIA_TYPE_ID", nullable = false)
	public Integer getMediaTypeId() {
		return this.mediaTypeId;
	}

	public void setMediaTypeId(Integer mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	@Column(name = "OPTION_MEDIA", nullable = false)
	public byte[] getOptionMedia() {
		return this.optionMedia;
	}

	public void setOptionMedia(byte[] optionMedia) {
		this.optionMedia = optionMedia;
	}

}
