package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AnswerReferenceMediaEntity generated by hbm2java
 */
@Entity
@Table(name = "ANSWER_REFERENCE_MEDIA", catalog = "qme")
public class AnswerReferenceMediaEntity implements java.io.Serializable {

	private static final long serialVersionUID = 5127686293574230507L;
	
	private Long answerRefMediaId;
	private Long questionId;
	private Integer mediaTypeId;
	private String refMediaMime;
	private byte[] refMedia;

	public AnswerReferenceMediaEntity() {
	}

	public AnswerReferenceMediaEntity(Long questionId, Integer mediaTypeId,
			String refMediaMime, byte[] refMedia) {
		this.questionId = questionId;
		this.mediaTypeId = mediaTypeId;
		this.refMediaMime = refMediaMime;
		this.refMedia = refMedia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ANSWER_REF_MEDIA_ID", unique = true, nullable = false)
	public Long getAnswerRefMediaId() {
		return this.answerRefMediaId;
	}

	public void setAnswerRefMediaId(Long answerRefMediaId) {
		this.answerRefMediaId = answerRefMediaId;
	}

	@Column(name = "QUESTION_ID", nullable = false)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@Column(name = "MEDIA_TYPE_ID", nullable = false)
	public Integer getMediaTypeId() {
		return this.mediaTypeId;
	}

	public void setMediaTypeId(Integer mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	@Column(name = "REF_MEDIA_MIME", nullable = false, length = 150)
	public String getRefMediaMime() {
		return this.refMediaMime;
	}

	public void setRefMediaMime(String refMediaMime) {
		this.refMediaMime = refMediaMime;
	}

	@Column(name = "REF_MEDIA", nullable = false)
	public byte[] getRefMedia() {
		return this.refMedia;
	}

	public void setRefMedia(byte[] refMedia) {
		this.refMedia = refMedia;
	}

}
