/**
 * Name      : com.malcolm.qme.springdata.entity.Category.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : Category Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "CATEGORY", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "CAT_NAME"))
public class Category implements java.io.Serializable {

	private static final long serialVersionUID = -5777006509366362337L;
	
	private Integer catId;
	private String catName;
	private int catParentId;
	private Date catCreateDate;
	private int catCreateUser;
	private Date catUpdateDate;
	private int catUpdateUser;
	private Integer catLikes;

	public Category() {
	}

	public Category(String catName, int catParentId, Date catCreateDate,
			int catCreateUser, Date catUpdateDate, int catUpdateUser) {
		this.catName = catName;
		this.catParentId = catParentId;
		this.catCreateDate = catCreateDate;
		this.catCreateUser = catCreateUser;
		this.catUpdateDate = catUpdateDate;
		this.catUpdateUser = catUpdateUser;
	}

	public Category(String catName, int catParentId, Date catCreateDate,
			int catCreateUser, Date catUpdateDate, int catUpdateUser,
			Integer catLikes) {
		this.catName = catName;
		this.catParentId = catParentId;
		this.catCreateDate = catCreateDate;
		this.catCreateUser = catCreateUser;
		this.catUpdateDate = catUpdateDate;
		this.catUpdateUser = catUpdateUser;
		this.catLikes = catLikes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CAT_ID", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "CAT_NAME", unique = true, nullable = false, length = 150)
	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	@Column(name = "CAT_PARENT_ID", nullable = false)
	public int getCatParentId() {
		return this.catParentId;
	}

	public void setCatParentId(int catParentId) {
		this.catParentId = catParentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAT_CREATE_DATE", nullable = false, length = 19)
	public Date getCatCreateDate() {
		return this.catCreateDate;
	}

	public void setCatCreateDate(Date catCreateDate) {
		this.catCreateDate = catCreateDate;
	}

	@Column(name = "CAT_CREATE_USER", nullable = false)
	public int getCatCreateUser() {
		return this.catCreateUser;
	}

	public void setCatCreateUser(int catCreateUser) {
		this.catCreateUser = catCreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAT_UPDATE_DATE", nullable = false, length = 19)
	public Date getCatUpdateDate() {
		return this.catUpdateDate;
	}

	public void setCatUpdateDate(Date catUpdateDate) {
		this.catUpdateDate = catUpdateDate;
	}

	@Column(name = "CAT_UPDATE_USER", nullable = false)
	public int getCatUpdateUser() {
		return this.catUpdateUser;
	}

	public void setCatUpdateUser(int catUpdateUser) {
		this.catUpdateUser = catUpdateUser;
	}

	@Column(name = "CAT_LIKES")
	public Integer getCatLikes() {
		return this.catLikes;
	}

	public void setCatLikes(Integer catLikes) {
		this.catLikes = catLikes;
	}

}
