package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 10:39:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CategoryEntity generated by hbm2java
 */
@Entity
@Table(name = "CATEGORY", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "CAT_NAME"))
public class CategoryEntity implements java.io.Serializable {

	private static final long serialVersionUID = 7450015211498125076L;
	
	private Long catId;
	private String catName;
	private Long catParentId;
	private Date catCreateDate;
	private Long catCreateUser;
	private Date catUpdateDate;
	private Long catUpdateUser;
	private Long catLikes;

	public CategoryEntity() {
	}

	public CategoryEntity(String catName, Long catParentId, Date catCreateDate,
			Long catCreateUser, Date catUpdateDate, Long catUpdateUser) {
		this.catName = catName;
		this.catParentId = catParentId;
		this.catCreateDate = catCreateDate;
		this.catCreateUser = catCreateUser;
		this.catUpdateDate = catUpdateDate;
		this.catUpdateUser = catUpdateUser;
	}

	public CategoryEntity(String catName, Long catParentId, Date catCreateDate,
			Long catCreateUser, Date catUpdateDate, Long catUpdateUser,
			Long catLikes) {
		this.catName = catName;
		this.catParentId = catParentId;
		this.catCreateDate = catCreateDate;
		this.catCreateUser = catCreateUser;
		this.catUpdateDate = catUpdateDate;
		this.catUpdateUser = catUpdateUser;
		this.catLikes = catLikes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CAT_ID", unique = true, nullable = false)
	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	@Column(name = "CAT_NAME", unique = true, nullable = false, length = 150)
	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	@Column(name = "CAT_PARENT_ID", nullable = false)
	public Long getCatParentId() {
		return this.catParentId;
	}

	public void setCatParentId(Long catParentId) {
		this.catParentId = catParentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAT_CREATE_DATE", nullable = false, length = 19)
	public Date getCatCreateDate() {
		return this.catCreateDate;
	}

	public void setCatCreateDate(Date catCreateDate) {
		this.catCreateDate = catCreateDate;
	}

	@Column(name = "CAT_CREATE_USER", nullable = false)
	public Long getCatCreateUser() {
		return this.catCreateUser;
	}

	public void setCatCreateUser(Long catCreateUser) {
		this.catCreateUser = catCreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAT_UPDATE_DATE", nullable = false, length = 19)
	public Date getCatUpdateDate() {
		return this.catUpdateDate;
	}

	public void setCatUpdateDate(Date catUpdateDate) {
		this.catUpdateDate = catUpdateDate;
	}

	@Column(name = "CAT_UPDATE_USER", nullable = false)
	public Long getCatUpdateUser() {
		return this.catUpdateUser;
	}

	public void setCatUpdateUser(Long catUpdateUser) {
		this.catUpdateUser = catUpdateUser;
	}

	@Column(name = "CAT_LIKES")
	public Long getCatLikes() {
		return this.catLikes;
	}

	public void setCatLikes(Long catLikes) {
		this.catLikes = catLikes;
	}

}
