package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * CategoryEntity generated by hbm2java
 */
public class CategoryEntity implements java.io.Serializable {

	private static final long serialVersionUID = 7450015211498125076L;
	
	private Long catId;
	private String catName;
	private Long catParentId;
	private Date catCreateDate;
	private Long catCreateUser;
	private Date catUpdateDate;
	private Long catUpdateUser;
	private Long catLikes;

	public CategoryEntity() {
	}

	public CategoryEntity(String catName, Long catParentId, Date catCreateDate,
			Long catCreateUser, Date catUpdateDate, Long catUpdateUser) {
		this.catName = catName;
		this.catParentId = catParentId;
		this.catCreateDate = catCreateDate;
		this.catCreateUser = catCreateUser;
		this.catUpdateDate = catUpdateDate;
		this.catUpdateUser = catUpdateUser;
	}

	public CategoryEntity(String catName, Long catParentId, Date catCreateDate,
			Long catCreateUser, Date catUpdateDate, Long catUpdateUser,
			Long catLikes) {
		this.catName = catName;
		this.catParentId = catParentId;
		this.catCreateDate = catCreateDate;
		this.catCreateUser = catCreateUser;
		this.catUpdateDate = catUpdateDate;
		this.catUpdateUser = catUpdateUser;
		this.catLikes = catLikes;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public Long getCatParentId() {
		return this.catParentId;
	}

	public void setCatParentId(Long catParentId) {
		this.catParentId = catParentId;
	}

	public Date getCatCreateDate() {
		return this.catCreateDate;
	}

	public void setCatCreateDate(Date catCreateDate) {
		this.catCreateDate = catCreateDate;
	}

	public Long getCatCreateUser() {
		return this.catCreateUser;
	}

	public void setCatCreateUser(Long catCreateUser) {
		this.catCreateUser = catCreateUser;
	}

	public Date getCatUpdateDate() {
		return this.catUpdateDate;
	}

	public void setCatUpdateDate(Date catUpdateDate) {
		this.catUpdateDate = catUpdateDate;
	}

	public Long getCatUpdateUser() {
		return this.catUpdateUser;
	}

	public void setCatUpdateUser(Long catUpdateUser) {
		this.catUpdateUser = catUpdateUser;
	}

	public Long getCatLikes() {
		return this.catLikes;
	}

	public void setCatLikes(Long catLikes) {
		this.catLikes = catLikes;
	}

}
