package com.malcolm.qme.springdata.entity;

// Generated May 16, 2015 7:28:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MediaTypeEntity generated by hbm2java
 */
@Entity
@Table(name = "MEDIA_TYPE", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "MEDIA_MIME_TYPE"))
public class MediaTypeEntity implements java.io.Serializable {


	private static final long serialVersionUID = -3293971500327209006L;

	private Integer mediaTypeId;
	private String mediaMimeType;

	public MediaTypeEntity() {
	}

	public MediaTypeEntity(String mediaMimeType) {
		this.mediaMimeType = mediaMimeType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MEDIA_TYPE_ID", unique = true, nullable = false)
	public Integer getMediaTypeId() {
		return this.mediaTypeId;
	}

	public void setMediaTypeId(Integer mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	@Column(name = "MEDIA_MIME_TYPE", unique = true, nullable = false, length = 50)
	public String getMediaMimeType() {
		return this.mediaMimeType;
	}

	public void setMediaMimeType(String mediaMimeType) {
		this.mediaMimeType = mediaMimeType;
	}

}
