package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MediaTypeEntity generated by hbm2java
 */
@Entity
@Table(name = "MEDIA_TYPE", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "MEDIA_TYPE"))
public class MediaTypeEntity implements java.io.Serializable {

	private static final long serialVersionUID = -1629717987829526770L;
	
	private Integer mediaTypeId;
	private String mediaType;
	private String mediaTypeDesc;

	public MediaTypeEntity() {
	}

	public MediaTypeEntity(String mediaType) {
		this.mediaType = mediaType;
	}

	public MediaTypeEntity(String mediaType, String mediaTypeDesc) {
		this.mediaType = mediaType;
		this.mediaTypeDesc = mediaTypeDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MEDIA_TYPE_ID", unique = true, nullable = false)
	public Integer getMediaTypeId() {
		return this.mediaTypeId;
	}

	public void setMediaTypeId(Integer mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	@Column(name = "MEDIA_TYPE", unique = true, nullable = false, length = 50)
	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "MEDIA_TYPE_DESC")
	public String getMediaTypeDesc() {
		return this.mediaTypeDesc;
	}

	public void setMediaTypeDesc(String mediaTypeDesc) {
		this.mediaTypeDesc = mediaTypeDesc;
	}

}
