package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * QuestionHitEntity generated by hbm2java
 */
public class QuestionHitEntity implements java.io.Serializable {

	private static final long serialVersionUID = 5786219888513685818L;
	
	private Long questionId;
	private Long catId;
	private Long questionHit;
	private Long rightCount;
	private Long wrongCount;

	public QuestionHitEntity() {
	}

	public QuestionHitEntity(Long questionId, Long catId, Long questionHit,
			Long rightCount, Long wrongCount) {
		this.questionId = questionId;
		this.catId = catId;
		this.questionHit = questionHit;
		this.rightCount = rightCount;
		this.wrongCount = wrongCount;
	}

	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	public Long getQuestionHit() {
		return this.questionHit;
	}

	public void setQuestionHit(Long questionHit) {
		this.questionHit = questionHit;
	}

	public Long getRightCount() {
		return this.rightCount;
	}

	public void setRightCount(Long rightCount) {
		this.rightCount = rightCount;
	}

	public Long getWrongCount() {
		return this.wrongCount;
	}

	public void setWrongCount(Long wrongCount) {
		this.wrongCount = wrongCount;
	}

}
