package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionEntity generated by hbm2java
 */
@Entity
@Table(name = "QUESTION", catalog = "qme")
public class QuestionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 9087848230244027291L;
	
	private Long questionId;
	private Long catId;
	private String questionText;
	private String questionAnswer;
	private Long questionLikes;
	private Date questionCreateDate;
	private Long questionCreateUser;
	private Date questionUpdateDate;
	private Long questionUpdateUser;

	public QuestionEntity() {
	}

	public QuestionEntity(Long catId, String questionText, Long questionLikes,
			Date questionCreateDate, Long questionCreateUser,
			Date questionUpdateDate, Long questionUpdateUser) {
		this.catId = catId;
		this.questionText = questionText;
		this.questionLikes = questionLikes;
		this.questionCreateDate = questionCreateDate;
		this.questionCreateUser = questionCreateUser;
		this.questionUpdateDate = questionUpdateDate;
		this.questionUpdateUser = questionUpdateUser;
	}

	public QuestionEntity(Long catId, String questionText,
			String questionAnswer, Long questionLikes, Date questionCreateDate,
			Long questionCreateUser, Date questionUpdateDate,
			Long questionUpdateUser) {
		this.catId = catId;
		this.questionText = questionText;
		this.questionAnswer = questionAnswer;
		this.questionLikes = questionLikes;
		this.questionCreateDate = questionCreateDate;
		this.questionCreateUser = questionCreateUser;
		this.questionUpdateDate = questionUpdateDate;
		this.questionUpdateUser = questionUpdateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUESTION_ID", unique = true, nullable = false)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	@Column(name = "QUESTION_TEXT", nullable = false, length = 65535)
	public String getQuestionText() {
		return this.questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	@Column(name = "QUESTION_ANSWER")
	public String getQuestionAnswer() {
		return this.questionAnswer;
	}

	public void setQuestionAnswer(String questionAnswer) {
		this.questionAnswer = questionAnswer;
	}

	@Column(name = "QUESTION_LIKES", nullable = false)
	public Long getQuestionLikes() {
		return this.questionLikes;
	}

	public void setQuestionLikes(Long questionLikes) {
		this.questionLikes = questionLikes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUESTION_CREATE_DATE", nullable = false, length = 19)
	public Date getQuestionCreateDate() {
		return this.questionCreateDate;
	}

	public void setQuestionCreateDate(Date questionCreateDate) {
		this.questionCreateDate = questionCreateDate;
	}

	@Column(name = "QUESTION_CREATE_USER", nullable = false)
	public Long getQuestionCreateUser() {
		return this.questionCreateUser;
	}

	public void setQuestionCreateUser(Long questionCreateUser) {
		this.questionCreateUser = questionCreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUESTION_UPDATE_DATE", nullable = false, length = 19)
	public Date getQuestionUpdateDate() {
		return this.questionUpdateDate;
	}

	public void setQuestionUpdateDate(Date questionUpdateDate) {
		this.questionUpdateDate = questionUpdateDate;
	}

	@Column(name = "QUESTION_UPDATE_USER", nullable = false)
	public Long getQuestionUpdateUser() {
		return this.questionUpdateUser;
	}

	public void setQuestionUpdateUser(Long questionUpdateUser) {
		this.questionUpdateUser = questionUpdateUser;
	}

}
