/**
 * Name      : com.malcolm.qme.springdata.entity.Question.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : Question Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "QUESTION", catalog = "qme")
public class Question implements java.io.Serializable {

	private static final long serialVersionUID = -3717740254932115775L;
	
	private Integer questionId;
	private int catId;
	private String questionText;
	private String questionAnswer;
	private int questionLikes;
	private Date questionCreateDate;
	private int questionCreateUser;
	private Date questionUpdateDate;
	private int questionUpdateUser;

	public Question() {
	}

	public Question(int catId, String questionText, int questionLikes,
			Date questionCreateDate, int questionCreateUser,
			Date questionUpdateDate, int questionUpdateUser) {
		this.catId = catId;
		this.questionText = questionText;
		this.questionLikes = questionLikes;
		this.questionCreateDate = questionCreateDate;
		this.questionCreateUser = questionCreateUser;
		this.questionUpdateDate = questionUpdateDate;
		this.questionUpdateUser = questionUpdateUser;
	}

	public Question(int catId, String questionText, String questionAnswer,
			int questionLikes, Date questionCreateDate, int questionCreateUser,
			Date questionUpdateDate, int questionUpdateUser) {
		this.catId = catId;
		this.questionText = questionText;
		this.questionAnswer = questionAnswer;
		this.questionLikes = questionLikes;
		this.questionCreateDate = questionCreateDate;
		this.questionCreateUser = questionCreateUser;
		this.questionUpdateDate = questionUpdateDate;
		this.questionUpdateUser = questionUpdateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUESTION_ID", unique = true, nullable = false)
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Column(name = "QUESTION_TEXT", nullable = false, length = 65535)
	public String getQuestionText() {
		return this.questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	@Column(name = "QUESTION_ANSWER")
	public String getQuestionAnswer() {
		return this.questionAnswer;
	}

	public void setQuestionAnswer(String questionAnswer) {
		this.questionAnswer = questionAnswer;
	}

	@Column(name = "QUESTION_LIKES", nullable = false)
	public int getQuestionLikes() {
		return this.questionLikes;
	}

	public void setQuestionLikes(int questionLikes) {
		this.questionLikes = questionLikes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUESTION_CREATE_DATE", nullable = false, length = 19)
	public Date getQuestionCreateDate() {
		return this.questionCreateDate;
	}

	public void setQuestionCreateDate(Date questionCreateDate) {
		this.questionCreateDate = questionCreateDate;
	}

	@Column(name = "QUESTION_CREATE_USER", nullable = false)
	public int getQuestionCreateUser() {
		return this.questionCreateUser;
	}

	public void setQuestionCreateUser(int questionCreateUser) {
		this.questionCreateUser = questionCreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUESTION_UPDATE_DATE", nullable = false, length = 19)
	public Date getQuestionUpdateDate() {
		return this.questionUpdateDate;
	}

	public void setQuestionUpdateDate(Date questionUpdateDate) {
		this.questionUpdateDate = questionUpdateDate;
	}

	@Column(name = "QUESTION_UPDATE_USER", nullable = false)
	public int getQuestionUpdateUser() {
		return this.questionUpdateUser;
	}

	public void setQuestionUpdateUser(int questionUpdateUser) {
		this.questionUpdateUser = questionUpdateUser;
	}

}
