package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * QuestionEntity generated by hbm2java
 */
public class QuestionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 9087848230244027291L;
	
	private Long questionId;
	private Long catId;
	private String questionText;
	private String questionAnswer;
	private Long questionLikes;
	private Date questionCreateDate;
	private Long questionCreateUser;
	private Date questionUpdateDate;
	private Long questionUpdateUser;

	public QuestionEntity() {
	}

	public QuestionEntity(Long catId, String questionText, Long questionLikes,
			Date questionCreateDate, Long questionCreateUser,
			Date questionUpdateDate, Long questionUpdateUser) {
		this.catId = catId;
		this.questionText = questionText;
		this.questionLikes = questionLikes;
		this.questionCreateDate = questionCreateDate;
		this.questionCreateUser = questionCreateUser;
		this.questionUpdateDate = questionUpdateDate;
		this.questionUpdateUser = questionUpdateUser;
	}

	public QuestionEntity(Long catId, String questionText,
			String questionAnswer, Long questionLikes, Date questionCreateDate,
			Long questionCreateUser, Date questionUpdateDate,
			Long questionUpdateUser) {
		this.catId = catId;
		this.questionText = questionText;
		this.questionAnswer = questionAnswer;
		this.questionLikes = questionLikes;
		this.questionCreateDate = questionCreateDate;
		this.questionCreateUser = questionCreateUser;
		this.questionUpdateDate = questionUpdateDate;
		this.questionUpdateUser = questionUpdateUser;
	}

	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	public String getQuestionText() {
		return this.questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	public String getQuestionAnswer() {
		return this.questionAnswer;
	}

	public void setQuestionAnswer(String questionAnswer) {
		this.questionAnswer = questionAnswer;
	}

	public Long getQuestionLikes() {
		return this.questionLikes;
	}

	public void setQuestionLikes(Long questionLikes) {
		this.questionLikes = questionLikes;
	}

	public Date getQuestionCreateDate() {
		return this.questionCreateDate;
	}

	public void setQuestionCreateDate(Date questionCreateDate) {
		this.questionCreateDate = questionCreateDate;
	}

	public Long getQuestionCreateUser() {
		return this.questionCreateUser;
	}

	public void setQuestionCreateUser(Long questionCreateUser) {
		this.questionCreateUser = questionCreateUser;
	}

	public Date getQuestionUpdateDate() {
		return this.questionUpdateDate;
	}

	public void setQuestionUpdateDate(Date questionUpdateDate) {
		this.questionUpdateDate = questionUpdateDate;
	}

	public Long getQuestionUpdateUser() {
		return this.questionUpdateUser;
	}

	public void setQuestionUpdateUser(Long questionUpdateUser) {
		this.questionUpdateUser = questionUpdateUser;
	}

}
