/**
 * Name      : com.malcolm.qme.springdata.entity.QuestionHitEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : QuestionHit Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QuestionHitEntity generated by hbm2java
 */
@Entity
@Table(name = "QUESTION_HIT", catalog = "qme")
public class QuestionHitEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7814830528253557435L;
	
	private int questionId;
	private int catId;
	private int questionHit;
	private int rightCount;
	private int wrongCount;

	public QuestionHitEntity() {
	}

	public QuestionHitEntity(int questionId, int catId, int questionHit,
							 int rightCount, int wrongCount) {
		this.questionId = questionId;
		this.catId = catId;
		this.questionHit = questionHit;
		this.rightCount = rightCount;
		this.wrongCount = wrongCount;
	}

	@Id
	@Column(name = "QUESTION_ID", unique = true, nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Column(name = "QUESTION_HIT", nullable = false)
	public int getQuestionHit() {
		return this.questionHit;
	}

	public void setQuestionHit(int questionHit) {
		this.questionHit = questionHit;
	}

	@Column(name = "RIGHT_COUNT", nullable = false)
	public int getRightCount() {
		return this.rightCount;
	}

	public void setRightCount(int rightCount) {
		this.rightCount = rightCount;
	}

	@Column(name = "WRONG_COUNT", nullable = false)
	public int getWrongCount() {
		return this.wrongCount;
	}

	public void setWrongCount(int wrongCount) {
		this.wrongCount = wrongCount;
	}

}
