/**
 * Name      : com.malcolm.qme.springdata.entity.QuizQuestionEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : QuizQuestion Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QuizQuestionEntity generated by hbm2java
 */
@Entity
@Table(name = "QUIZ_QUESTION", catalog = "qme")
public class QuizQuestionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 6707953542866408256L;
	
	private Integer quizQuestionId;
	private int quizId;
	private int questionId;

	public QuizQuestionEntity() {
	}

	public QuizQuestionEntity(int quizId, int questionId) {
		this.quizId = quizId;
		this.questionId = questionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUIZ_QUESTION_ID", unique = true, nullable = false)
	public Integer getQuizQuestionId() {
		return this.quizQuestionId;
	}

	public void setQuizQuestionId(Integer quizQuestionId) {
		this.quizQuestionId = quizQuestionId;
	}

	@Column(name = "QUIZ_ID", nullable = false)
	public int getQuizId() {
		return this.quizId;
	}

	public void setQuizId(int quizId) {
		this.quizId = quizId;
	}

	@Column(name = "QUESTION_ID", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

}
