package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QuizQuestionEntity generated by hbm2java
 */
@Entity
@Table(name = "QUIZ_QUESTION", catalog = "qme")
public class QuizQuestionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 2739649231157126325L;
	
	private Long quizQuestionId;
	private Long quizId;
	private Long questionId;

	public QuizQuestionEntity() {
	}

	public QuizQuestionEntity(Long quizId, Long questionId) {
		this.quizId = quizId;
		this.questionId = questionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUIZ_QUESTION_ID", unique = true, nullable = false)
	public Long getQuizQuestionId() {
		return this.quizQuestionId;
	}

	public void setQuizQuestionId(Long quizQuestionId) {
		this.quizQuestionId = quizQuestionId;
	}

	@Column(name = "QUIZ_ID", nullable = false)
	public Long getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Long quizId) {
		this.quizId = quizId;
	}

	@Column(name = "QUESTION_ID", nullable = false)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

}
