/**
 * Name      : com.malcolm.qme.springdata.entity.QuizEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : Quiz Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1

package com.malcolm.qme.springdata.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * QuizEntity generated by hbm2java
 */
@Entity
@Table(name = "QUIZ", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "QUIZ_NAME"))
public class QuizEntity implements java.io.Serializable {

	private static final long serialVersionUID = -8654794883612895110L;
	
	private Integer quizId;
	private String quizName;
	private String quizDesc;
	private int catId;
	private Integer quizHits;
	private int quizLikes;
	private byte maxAttempts;
	private Date quizCreateDate;
	private int quizCreateUser;
	private Date quizUpdateDate;
	private int quizUpdateUser;

	public QuizEntity() {
	}

	public QuizEntity(String quizName, int catId, int quizLikes, byte maxAttempts,
					  Date quizCreateDate, int quizCreateUser, Date quizUpdateDate,
					  int quizUpdateUser) {
		this.quizName = quizName;
		this.catId = catId;
		this.quizLikes = quizLikes;
		this.maxAttempts = maxAttempts;
		this.quizCreateDate = quizCreateDate;
		this.quizCreateUser = quizCreateUser;
		this.quizUpdateDate = quizUpdateDate;
		this.quizUpdateUser = quizUpdateUser;
	}

	public QuizEntity(String quizName, String quizDesc, int catId, Integer quizHits,
					  int quizLikes, byte maxAttempts, Date quizCreateDate,
					  int quizCreateUser, Date quizUpdateDate, int quizUpdateUser) {
		this.quizName = quizName;
		this.quizDesc = quizDesc;
		this.catId = catId;
		this.quizHits = quizHits;
		this.quizLikes = quizLikes;
		this.maxAttempts = maxAttempts;
		this.quizCreateDate = quizCreateDate;
		this.quizCreateUser = quizCreateUser;
		this.quizUpdateDate = quizUpdateDate;
		this.quizUpdateUser = quizUpdateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUIZ_ID", unique = true, nullable = false)
	public Integer getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Integer quizId) {
		this.quizId = quizId;
	}

	@Column(name = "QUIZ_NAME", unique = true, nullable = false, length = 60)
	public String getQuizName() {
		return this.quizName;
	}

	public void setQuizName(String quizName) {
		this.quizName = quizName;
	}

	@Column(name = "QUIZ_DESC", length = 756)
	public String getQuizDesc() {
		return this.quizDesc;
	}

	public void setQuizDesc(String quizDesc) {
		this.quizDesc = quizDesc;
	}

	@Column(name = "CAT_ID", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Column(name = "QUIZ_HITS")
	public Integer getQuizHits() {
		return this.quizHits;
	}

	public void setQuizHits(Integer quizHits) {
		this.quizHits = quizHits;
	}

	@Column(name = "QUIZ_LIKES", nullable = false)
	public int getQuizLikes() {
		return this.quizLikes;
	}

	public void setQuizLikes(int quizLikes) {
		this.quizLikes = quizLikes;
	}

	@Column(name = "MAX_ATTEMPTS", nullable = false)
	public byte getMaxAttempts() {
		return this.maxAttempts;
	}

	public void setMaxAttempts(byte maxAttempts) {
		this.maxAttempts = maxAttempts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_CREATE_DATE", nullable = false, length = 19)
	public Date getQuizCreateDate() {
		return this.quizCreateDate;
	}

	public void setQuizCreateDate(Date quizCreateDate) {
		this.quizCreateDate = quizCreateDate;
	}

	@Column(name = "QUIZ_CREATE_USER", nullable = false)
	public int getQuizCreateUser() {
		return this.quizCreateUser;
	}

	public void setQuizCreateUser(int quizCreateUser) {
		this.quizCreateUser = quizCreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_UPDATE_DATE", nullable = false, length = 19)
	public Date getQuizUpdateDate() {
		return this.quizUpdateDate;
	}

	public void setQuizUpdateDate(Date quizUpdateDate) {
		this.quizUpdateDate = quizUpdateDate;
	}

	@Column(name = "QUIZ_UPDATE_USER", nullable = false)
	public int getQuizUpdateUser() {
		return this.quizUpdateUser;
	}

	public void setQuizUpdateUser(int quizUpdateUser) {
		this.quizUpdateUser = quizUpdateUser;
	}

}
