package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * QuizQuestionEntity generated by hbm2java
 */
public class QuizQuestionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 2739649231157126325L;
	
	private Long quizQuestionId;
	private Long quizId;
	private Long questionId;

	public QuizQuestionEntity() {
	}

	public QuizQuestionEntity(Long quizId, Long questionId) {
		this.quizId = quizId;
		this.questionId = questionId;
	}

	public Long getQuizQuestionId() {
		return this.quizQuestionId;
	}

	public void setQuizQuestionId(Long quizQuestionId) {
		this.quizQuestionId = quizQuestionId;
	}

	public Long getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Long quizId) {
		this.quizId = quizId;
	}

	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

}
