package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 10:39:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * QuizEntity generated by hbm2java
 */
@Entity
@Table(name = "QUIZ", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "QUIZ_NAME"))
public class QuizEntity implements java.io.Serializable {

	private static final long serialVersionUID = -6004675333716243501L;
	
	private Long quizId;
	private String quizName;
	private String quizDesc;
	private Long catId;
	private Long quizHits;
	private Long quizLikes;
	private Integer maxAttempts;
	private Date quizCreateDate;
	private Long quizCreateUser;
	private Date quizUpdateDate;
	private Long quizUpdateUser;

	public QuizEntity() {
	}

	public QuizEntity(String quizName, Long catId, Long quizLikes,
			Integer maxAttempts, Date quizCreateDate, Long quizCreateUser,
			Date quizUpdateDate, Long quizUpdateUser) {
		this.quizName = quizName;
		this.catId = catId;
		this.quizLikes = quizLikes;
		this.maxAttempts = maxAttempts;
		this.quizCreateDate = quizCreateDate;
		this.quizCreateUser = quizCreateUser;
		this.quizUpdateDate = quizUpdateDate;
		this.quizUpdateUser = quizUpdateUser;
	}

	public QuizEntity(String quizName, String quizDesc, Long catId,
			Long quizHits, Long quizLikes, Integer maxAttempts,
			Date quizCreateDate, Long quizCreateUser, Date quizUpdateDate,
			Long quizUpdateUser) {
		this.quizName = quizName;
		this.quizDesc = quizDesc;
		this.catId = catId;
		this.quizHits = quizHits;
		this.quizLikes = quizLikes;
		this.maxAttempts = maxAttempts;
		this.quizCreateDate = quizCreateDate;
		this.quizCreateUser = quizCreateUser;
		this.quizUpdateDate = quizUpdateDate;
		this.quizUpdateUser = quizUpdateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUIZ_ID", unique = true, nullable = false)
	public Long getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Long quizId) {
		this.quizId = quizId;
	}

	@Column(name = "QUIZ_NAME", unique = true, nullable = false, length = 60)
	public String getQuizName() {
		return this.quizName;
	}

	public void setQuizName(String quizName) {
		this.quizName = quizName;
	}

	@Column(name = "QUIZ_DESC", length = 756)
	public String getQuizDesc() {
		return this.quizDesc;
	}

	public void setQuizDesc(String quizDesc) {
		this.quizDesc = quizDesc;
	}

	@Column(name = "CAT_ID", nullable = false)
	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	@Column(name = "QUIZ_HITS")
	public Long getQuizHits() {
		return this.quizHits;
	}

	public void setQuizHits(Long quizHits) {
		this.quizHits = quizHits;
	}

	@Column(name = "QUIZ_LIKES", nullable = false)
	public Long getQuizLikes() {
		return this.quizLikes;
	}

	public void setQuizLikes(Long quizLikes) {
		this.quizLikes = quizLikes;
	}

	@Column(name = "MAX_ATTEMPTS", nullable = false)
	public Integer getMaxAttempts() {
		return this.maxAttempts;
	}

	public void setMaxAttempts(Integer maxAttempts) {
		this.maxAttempts = maxAttempts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_CREATE_DATE", nullable = false, length = 19)
	public Date getQuizCreateDate() {
		return this.quizCreateDate;
	}

	public void setQuizCreateDate(Date quizCreateDate) {
		this.quizCreateDate = quizCreateDate;
	}

	@Column(name = "QUIZ_CREATE_USER", nullable = false)
	public Long getQuizCreateUser() {
		return this.quizCreateUser;
	}

	public void setQuizCreateUser(Long quizCreateUser) {
		this.quizCreateUser = quizCreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_UPDATE_DATE", nullable = false, length = 19)
	public Date getQuizUpdateDate() {
		return this.quizUpdateDate;
	}

	public void setQuizUpdateDate(Date quizUpdateDate) {
		this.quizUpdateDate = quizUpdateDate;
	}

	@Column(name = "QUIZ_UPDATE_USER", nullable = false)
	public Long getQuizUpdateUser() {
		return this.quizUpdateUser;
	}

	public void setQuizUpdateUser(Long quizUpdateUser) {
		this.quizUpdateUser = quizUpdateUser;
	}

}
