package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * QuizEntity generated by hbm2java
 */
public class QuizEntity implements java.io.Serializable {

	private static final long serialVersionUID = -6004675333716243501L;
	
	private Long quizId;
	private String quizName;
	private String quizDesc;
	private Long catId;
	private Long quizHits;
	private Long quizLikes;
	private Integer maxAttempts;
	private Date quizCreateDate;
	private Long quizCreateUser;
	private Date quizUpdateDate;
	private Long quizUpdateUser;

	public QuizEntity() {
	}

	public QuizEntity(String quizName, Long catId, Long quizLikes,
			Integer maxAttempts, Date quizCreateDate, Long quizCreateUser,
			Date quizUpdateDate, Long quizUpdateUser) {
		this.quizName = quizName;
		this.catId = catId;
		this.quizLikes = quizLikes;
		this.maxAttempts = maxAttempts;
		this.quizCreateDate = quizCreateDate;
		this.quizCreateUser = quizCreateUser;
		this.quizUpdateDate = quizUpdateDate;
		this.quizUpdateUser = quizUpdateUser;
	}

	public QuizEntity(String quizName, String quizDesc, Long catId,
			Long quizHits, Long quizLikes, Integer maxAttempts,
			Date quizCreateDate, Long quizCreateUser, Date quizUpdateDate,
			Long quizUpdateUser) {
		this.quizName = quizName;
		this.quizDesc = quizDesc;
		this.catId = catId;
		this.quizHits = quizHits;
		this.quizLikes = quizLikes;
		this.maxAttempts = maxAttempts;
		this.quizCreateDate = quizCreateDate;
		this.quizCreateUser = quizCreateUser;
		this.quizUpdateDate = quizUpdateDate;
		this.quizUpdateUser = quizUpdateUser;
	}

	public Long getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Long quizId) {
		this.quizId = quizId;
	}

	public String getQuizName() {
		return this.quizName;
	}

	public void setQuizName(String quizName) {
		this.quizName = quizName;
	}

	public String getQuizDesc() {
		return this.quizDesc;
	}

	public void setQuizDesc(String quizDesc) {
		this.quizDesc = quizDesc;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	public Long getQuizHits() {
		return this.quizHits;
	}

	public void setQuizHits(Long quizHits) {
		this.quizHits = quizHits;
	}

	public Long getQuizLikes() {
		return this.quizLikes;
	}

	public void setQuizLikes(Long quizLikes) {
		this.quizLikes = quizLikes;
	}

	public Integer getMaxAttempts() {
		return this.maxAttempts;
	}

	public void setMaxAttempts(Integer maxAttempts) {
		this.maxAttempts = maxAttempts;
	}

	public Date getQuizCreateDate() {
		return this.quizCreateDate;
	}

	public void setQuizCreateDate(Date quizCreateDate) {
		this.quizCreateDate = quizCreateDate;
	}

	public Long getQuizCreateUser() {
		return this.quizCreateUser;
	}

	public void setQuizCreateUser(Long quizCreateUser) {
		this.quizCreateUser = quizCreateUser;
	}

	public Date getQuizUpdateDate() {
		return this.quizUpdateDate;
	}

	public void setQuizUpdateDate(Date quizUpdateDate) {
		this.quizUpdateDate = quizUpdateDate;
	}

	public Long getQuizUpdateUser() {
		return this.quizUpdateUser;
	}

	public void setQuizUpdateUser(Long quizUpdateUser) {
		this.quizUpdateUser = quizUpdateUser;
	}

}
