/**
 * Name      : com.malcolm.qme.springdata.entity.RoleEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : Role Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RoleEntity generated by hbm2java
 */
@Entity
@Table(name = "ROLE", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "ROLE_NAME"))
public class RoleEntity implements java.io.Serializable {

	private static final long serialVersionUID = 4794585588499912394L;
	
	private Integer roleId;
	private String roleName;
	private String roleDesc;

	public RoleEntity() {
	}

	public RoleEntity(String roleName, String roleDesc) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ROLE_NAME", unique = true, nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ROLE_DESC", nullable = false, length = 128)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

}
