package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserQuizGameEntityId generated by hbm2java
 */
@Embeddable
public class UserQuizGameEntityId implements java.io.Serializable {

	private static final long serialVersionUID = 7631787668803094636L;

	private Long userId;
	private Long catId;
	private Long quizGameToken;

	public UserQuizGameEntityId() {
	}

	public UserQuizGameEntityId(Long userId, Long catId, Long quizGameToken) {
		this.userId = userId;
		this.catId = catId;
		this.quizGameToken = quizGameToken;
	}

	@Column(name = "USER_ID", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	@Column(name = "QUIZ_GAME_TOKEN", nullable = false)
	public Long getQuizGameToken() {
		return this.quizGameToken;
	}

	public void setQuizGameToken(Long quizGameToken) {
		this.quizGameToken = quizGameToken;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof UserQuizGameEntityId)) {
			return false;
		}
		final UserQuizGameEntityId castOther = (UserQuizGameEntityId) other;

		return ((this.getUserId() == castOther.getUserId()) || ((this
				.getUserId() != null) && (castOther.getUserId() != null) && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getCatId().equals(castOther.getCatId())) || ((this
						.getCatId() != null) && (castOther.getCatId() != null) && this
						.getCatId().equals(castOther.getCatId())))
						&& ((this.getQuizGameToken().equals(castOther.getQuizGameToken())) || ((this
								.getQuizGameToken() != null)
								&& (castOther.getQuizGameToken() != null) && this
								.getQuizGameToken()
								.equals(castOther.getQuizGameToken())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = (37 * result)
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = (37 * result)
				+ (getCatId() == null ? 0 : this.getCatId().hashCode());
		result = (37
				* result)
				+ (getQuizGameToken() == null ? 0 : this.getQuizGameToken()
						.hashCode());
		return result;
	}

}
