package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * UserQuizGameEntityId generated by hbm2java
 */
public class UserQuizGameEntityId implements java.io.Serializable {

	
	private static final long serialVersionUID = 7631787668803094636L;
	
	private Long userId;
	private Long catId;
	private Long quizGameToken;

	public UserQuizGameEntityId() {
	}

	public UserQuizGameEntityId(Long userId, Long catId, Long quizGameToken) {
		this.userId = userId;
		this.catId = catId;
		this.quizGameToken = quizGameToken;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	public Long getQuizGameToken() {
		return this.quizGameToken;
	}

	public void setQuizGameToken(Long quizGameToken) {
		this.quizGameToken = quizGameToken;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserQuizGameEntityId))
			return false;
		UserQuizGameEntityId castOther = (UserQuizGameEntityId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getCatId() == castOther.getCatId()) || (this
						.getCatId() != null && castOther.getCatId() != null && this
						.getCatId().equals(castOther.getCatId())))
				&& ((this.getQuizGameToken() == castOther.getQuizGameToken()) || (this
						.getQuizGameToken() != null
						&& castOther.getQuizGameToken() != null && this
						.getQuizGameToken()
						.equals(castOther.getQuizGameToken())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getCatId() == null ? 0 : this.getCatId().hashCode());
		result = 37
				* result
				+ (getQuizGameToken() == null ? 0 : this.getQuizGameToken()
						.hashCode());
		return result;
	}

}
