/**
 * Name      : com.malcolm.qme.springdata.entity.UserQuizLikesId.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserQuizLikesId Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserQuizLikesId generated by hbm2java
 */
@Embeddable
public class UserQuizLikesId implements java.io.Serializable {

	
	private static final long serialVersionUID = -5956065779150297368L;
	
	private int userId;
	private int quizId;

	public UserQuizLikesId() {
	}

	public UserQuizLikesId(int userId, int quizId) {
		this.userId = userId;
		this.quizId = quizId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "QUIZ_ID", nullable = false)
	public int getQuizId() {
		return this.quizId;
	}

	public void setQuizId(int quizId) {
		this.quizId = quizId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserQuizLikesId))
			return false;
		UserQuizLikesId castOther = (UserQuizLikesId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getQuizId() == castOther.getQuizId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getQuizId();
		return result;
	}

}
