/**
 * Name      : com.malcolm.qme.springdata.entity.UserQuestionLikes.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserQuestionLikes Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserQuestionLikes generated by hbm2java
 */
@Entity
@Table(name = "USER_QUESTION_LIKES", catalog = "qme")
public class UserQuestionLikes implements java.io.Serializable {

	private static final long serialVersionUID = 1285398878109123002L;
	
	private UserQuestionLikesId id;

	public UserQuestionLikes() {
	}

	public UserQuestionLikes(UserQuestionLikesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "questionId", column = @Column(name = "QUESTION_ID", nullable = false)) })
	public UserQuestionLikesId getId() {
		return this.id;
	}

	public void setId(UserQuestionLikesId id) {
		this.id = id;
	}

}
