package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * UserCategoryEntity generated by hbm2java
 */
public class UserCategoryEntity implements java.io.Serializable {

	private static final long serialVersionUID = 850550490881060729L;
	
	private Long userCatId;
	private Long userId;
	private Long catId;

	public UserCategoryEntity() {
	}

	public UserCategoryEntity(Long userId, Long catId) {
		this.userId = userId;
		this.catId = catId;
	}

	public Long getUserCatId() {
		return this.userCatId;
	}

	public void setUserCatId(Long userCatId) {
		this.userCatId = userCatId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

}
