package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * UserCategoryLikesEntityId generated by hbm2java
 */
public class UserCategoryLikesEntityId implements java.io.Serializable {

	private static final long serialVersionUID = -4470609228632391708L;
	
	private Long userId;
	private Long catId;

	public UserCategoryLikesEntityId() {
	}

	public UserCategoryLikesEntityId(Long userId, Long catId) {
		this.userId = userId;
		this.catId = catId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserCategoryLikesEntityId))
			return false;
		UserCategoryLikesEntityId castOther = (UserCategoryLikesEntityId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getCatId() == castOther.getCatId()) || (this
						.getCatId() != null && castOther.getCatId() != null && this
						.getCatId().equals(castOther.getCatId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getCatId() == null ? 0 : this.getCatId().hashCode());
		return result;
	}

}
