package com.malcolm.qme.springdata.entity;

// Generated May 18, 2015 7:53:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserQuizEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_QUIZ", catalog = "qme")
public class UserQuizEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7214565628037365166L;

	private Long userQuizId;
	private Long userId;
	private Long quizId;
	private Long catId;
	private Date quizStartDate;
	private Date quizEndDate;
	private Integer quizUserScore;
	private Integer quizMaxScore;
	private String quizToken;
	private byte quizComplete;

	public UserQuizEntity() {
	}

	public UserQuizEntity(Long userId, Long quizId, Long catId,
			Date quizStartDate, Integer quizUserScore, Integer quizMaxScore,
			byte quizComplete) {
		this.userId = userId;
		this.quizId = quizId;
		this.catId = catId;
		this.quizStartDate = quizStartDate;
		this.quizUserScore = quizUserScore;
		this.quizMaxScore = quizMaxScore;
		this.quizComplete = quizComplete;
	}

	public UserQuizEntity(Long userId, Long quizId, Long catId,
			Date quizStartDate, Date quizEndDate, Integer quizUserScore,
			Integer quizMaxScore, String quizToken, byte quizComplete) {
		this.userId = userId;
		this.quizId = quizId;
		this.catId = catId;
		this.quizStartDate = quizStartDate;
		this.quizEndDate = quizEndDate;
		this.quizUserScore = quizUserScore;
		this.quizMaxScore = quizMaxScore;
		this.quizToken = quizToken;
		this.quizComplete = quizComplete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_QUIZ_ID", unique = true, nullable = false)
	public Long getUserQuizId() {
		return this.userQuizId;
	}

	public void setUserQuizId(Long userQuizId) {
		this.userQuizId = userQuizId;
	}

	@Column(name = "USER_ID", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "QUIZ_ID", nullable = false)
	public Long getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Long quizId) {
		this.quizId = quizId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_START_DATE", nullable = false, length = 19)
	public Date getQuizStartDate() {
		return this.quizStartDate;
	}

	public void setQuizStartDate(Date quizStartDate) {
		this.quizStartDate = quizStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_END_DATE", length = 19)
	public Date getQuizEndDate() {
		return this.quizEndDate;
	}

	public void setQuizEndDate(Date quizEndDate) {
		this.quizEndDate = quizEndDate;
	}

	@Column(name = "QUIZ_USER_SCORE", nullable = false)
	public Integer getQuizUserScore() {
		return this.quizUserScore;
	}

	public void setQuizUserScore(Integer quizUserScore) {
		this.quizUserScore = quizUserScore;
	}

	@Column(name = "QUIZ_MAX_SCORE", nullable = false)
	public Integer getQuizMaxScore() {
		return this.quizMaxScore;
	}

	public void setQuizMaxScore(Integer quizMaxScore) {
		this.quizMaxScore = quizMaxScore;
	}

	@Column(name = "QUIZ_TOKEN", length = 256)
	public String getQuizToken() {
		return this.quizToken;
	}

	public void setQuizToken(String quizToken) {
		this.quizToken = quizToken;
	}

	@Column(name = "QUIZ_COMPLETE", nullable = false)
	public byte getQuizComplete() {
		return this.quizComplete;
	}

	public void setQuizComplete(byte quizComplete) {
		this.quizComplete = quizComplete;
	}

}
