package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * UserRolesEntity generated by hbm2java
 */
public class UserRolesEntity implements java.io.Serializable {

	private static final long serialVersionUID = -3150528334067090025L;
	
	private Long userRoleId;
	private Long userId;
	private Integer roleId;

	public UserRolesEntity() {
	}

	public UserRolesEntity(Long userId, Integer roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	public Long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Long userRoleId) {
		this.userRoleId = userRoleId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
