package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 10:39:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserQuizLikesEntityId generated by hbm2java
 */
@Embeddable
public class UserQuizLikesEntityId implements java.io.Serializable {

	private static final long serialVersionUID = -2710987586087887522L;
	
	private Long userId;
	private Long quizId;

	public UserQuizLikesEntityId() {
	}

	public UserQuizLikesEntityId(Long userId, Long quizId) {
		this.userId = userId;
		this.quizId = quizId;
	}

	@Column(name = "USER_ID", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "QUIZ_ID", nullable = false)
	public Long getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Long quizId) {
		this.quizId = quizId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserQuizLikesEntityId))
			return false;
		UserQuizLikesEntityId castOther = (UserQuizLikesEntityId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getQuizId() == castOther.getQuizId()) || (this
						.getQuizId() != null && castOther.getQuizId() != null && this
						.getQuizId().equals(castOther.getQuizId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getQuizId() == null ? 0 : this.getQuizId().hashCode());
		return result;
	}

}
