package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * UserCategoryLikesEntity generated by hbm2java
 */
public class UserCategoryLikesEntity implements java.io.Serializable {

	private static final long serialVersionUID = 3588585992432983653L;
	
	private UserCategoryLikesEntityId id;

	public UserCategoryLikesEntity() {
	}

	public UserCategoryLikesEntity(UserCategoryLikesEntityId id) {
		this.id = id;
	}

	public UserCategoryLikesEntityId getId() {
		return this.id;
	}

	public void setId(UserCategoryLikesEntityId id) {
		this.id = id;
	}

}
