package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserQuizLikesEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_QUIZ_LIKES", catalog = "qme")
public class UserQuizLikesEntity implements java.io.Serializable {

	
	private static final long serialVersionUID = -7764698214631748355L;
	
	private UserQuizLikesEntityId id;

	public UserQuizLikesEntity() {
	}

	public UserQuizLikesEntity(UserQuizLikesEntityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "quizId", column = @Column(name = "QUIZ_ID", nullable = false)) })
	public UserQuizLikesEntityId getId() {
		return this.id;
	}

	public void setId(UserQuizLikesEntityId id) {
		this.id = id;
	}

}
