package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserQuestionLikesEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_QUESTION_LIKES", catalog = "qme")
public class UserQuestionLikesEntity implements java.io.Serializable {

	
	private static final long serialVersionUID = -5649195723277241965L;
	
	private UserQuestionLikesEntityId id;

	public UserQuestionLikesEntity() {
	}

	public UserQuestionLikesEntity(UserQuestionLikesEntityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "questionId", column = @Column(name = "QUESTION_ID", nullable = false)) })
	public UserQuestionLikesEntityId getId() {
		return this.id;
	}

	public void setId(UserQuestionLikesEntityId id) {
		this.id = id;
	}

}
