/**
 * Name      : com.malcolm.qme.springdata.entity.UserQuizEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserQuiz Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1

package com.malcolm.qme.springdata.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserQuizEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_QUIZ", catalog = "qme")
public class UserQuizEntity implements java.io.Serializable {

	private static final long serialVersionUID = 5105525947321901403L;
	
	private Integer userQuizId;
	private int userId;
	private int quizId;
	private int catId;
	private Date quizStartDate;
	private Date quizEndDate;
	private int quizUserScore;
	private int quizMaxScore;
	private String quizToken;
	private byte quizComplete;

	public UserQuizEntity() {
	}

	public UserQuizEntity(int userId, int quizId, int catId, Date quizStartDate,
						  int quizUserScore, int quizMaxScore, byte quizComplete) {
		this.userId = userId;
		this.quizId = quizId;
		this.catId = catId;
		this.quizStartDate = quizStartDate;
		this.quizUserScore = quizUserScore;
		this.quizMaxScore = quizMaxScore;
		this.quizComplete = quizComplete;
	}

	public UserQuizEntity(int userId, int quizId, int catId, Date quizStartDate,
						  Date quizEndDate, int quizUserScore, int quizMaxScore,
						  String quizToken, byte quizComplete) {
		this.userId = userId;
		this.quizId = quizId;
		this.catId = catId;
		this.quizStartDate = quizStartDate;
		this.quizEndDate = quizEndDate;
		this.quizUserScore = quizUserScore;
		this.quizMaxScore = quizMaxScore;
		this.quizToken = quizToken;
		this.quizComplete = quizComplete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_QUIZ_ID", unique = true, nullable = false)
	public Integer getUserQuizId() {
		return this.userQuizId;
	}

	public void setUserQuizId(Integer userQuizId) {
		this.userQuizId = userQuizId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "QUIZ_ID", nullable = false)
	public int getQuizId() {
		return this.quizId;
	}

	public void setQuizId(int quizId) {
		this.quizId = quizId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_START_DATE", nullable = false, length = 19)
	public Date getQuizStartDate() {
		return this.quizStartDate;
	}

	public void setQuizStartDate(Date quizStartDate) {
		this.quizStartDate = quizStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUIZ_END_DATE", length = 19)
	public Date getQuizEndDate() {
		return this.quizEndDate;
	}

	public void setQuizEndDate(Date quizEndDate) {
		this.quizEndDate = quizEndDate;
	}

	@Column(name = "QUIZ_USER_SCORE", nullable = false)
	public int getQuizUserScore() {
		return this.quizUserScore;
	}

	public void setQuizUserScore(int quizUserScore) {
		this.quizUserScore = quizUserScore;
	}

	@Column(name = "QUIZ_MAX_SCORE", nullable = false)
	public int getQuizMaxScore() {
		return this.quizMaxScore;
	}

	public void setQuizMaxScore(int quizMaxScore) {
		this.quizMaxScore = quizMaxScore;
	}

	@Column(name = "QUIZ_TOKEN", length = 256)
	public String getQuizToken() {
		return this.quizToken;
	}

	public void setQuizToken(String quizToken) {
		this.quizToken = quizToken;
	}

	@Column(name = "QUIZ_COMPLETE", nullable = false)
	public byte getQuizComplete() {
		return this.quizComplete;
	}

	public void setQuizComplete(byte quizComplete) {
		this.quizComplete = quizComplete;
	}

}
