/**
 * Name      : com.malcolm.qme.springdata.entity.UserQuizLikes.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserQuizLikes Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserQuizLikes generated by hbm2java
 */
@Entity
@Table(name = "USER_QUIZ_LIKES", catalog = "qme")
public class UserQuizLikes implements java.io.Serializable {

	private static final long serialVersionUID = 8698133430254050234L;
	
	private UserQuizLikesId id;

	public UserQuizLikes() {
	}

	public UserQuizLikes(UserQuizLikesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "quizId", column = @Column(name = "QUIZ_ID", nullable = false)) })
	public UserQuizLikesId getId() {
		return this.id;
	}

	public void setId(UserQuizLikesId id) {
		this.id = id;
	}

}
