package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UserQuizEntity generated by hbm2java
 */
public class UserQuizEntity implements java.io.Serializable {

	
	private static final long serialVersionUID = -7214565628037365166L;
	
	private Long userQuizId;
	private Long userId;
	private Long quizId;
	private Long catId;
	private Date quizStartDate;
	private Date quizEndDate;
	private Integer quizUserScore;
	private Integer quizMaxScore;
	private String quizToken;
	private byte quizComplete;

	public UserQuizEntity() {
	}

	public UserQuizEntity(Long userId, Long quizId, Long catId,
			Date quizStartDate, Integer quizUserScore, Integer quizMaxScore,
			byte quizComplete) {
		this.userId = userId;
		this.quizId = quizId;
		this.catId = catId;
		this.quizStartDate = quizStartDate;
		this.quizUserScore = quizUserScore;
		this.quizMaxScore = quizMaxScore;
		this.quizComplete = quizComplete;
	}

	public UserQuizEntity(Long userId, Long quizId, Long catId,
			Date quizStartDate, Date quizEndDate, Integer quizUserScore,
			Integer quizMaxScore, String quizToken, byte quizComplete) {
		this.userId = userId;
		this.quizId = quizId;
		this.catId = catId;
		this.quizStartDate = quizStartDate;
		this.quizEndDate = quizEndDate;
		this.quizUserScore = quizUserScore;
		this.quizMaxScore = quizMaxScore;
		this.quizToken = quizToken;
		this.quizComplete = quizComplete;
	}

	public Long getUserQuizId() {
		return this.userQuizId;
	}

	public void setUserQuizId(Long userQuizId) {
		this.userQuizId = userQuizId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Long quizId) {
		this.quizId = quizId;
	}

	public Long getCatId() {
		return this.catId;
	}

	public void setCatId(Long catId) {
		this.catId = catId;
	}

	public Date getQuizStartDate() {
		return this.quizStartDate;
	}

	public void setQuizStartDate(Date quizStartDate) {
		this.quizStartDate = quizStartDate;
	}

	public Date getQuizEndDate() {
		return this.quizEndDate;
	}

	public void setQuizEndDate(Date quizEndDate) {
		this.quizEndDate = quizEndDate;
	}

	public Integer getQuizUserScore() {
		return this.quizUserScore;
	}

	public void setQuizUserScore(Integer quizUserScore) {
		this.quizUserScore = quizUserScore;
	}

	public Integer getQuizMaxScore() {
		return this.quizMaxScore;
	}

	public void setQuizMaxScore(Integer quizMaxScore) {
		this.quizMaxScore = quizMaxScore;
	}

	public String getQuizToken() {
		return this.quizToken;
	}

	public void setQuizToken(String quizToken) {
		this.quizToken = quizToken;
	}

	public byte getQuizComplete() {
		return this.quizComplete;
	}

	public void setQuizComplete(byte quizComplete) {
		this.quizComplete = quizComplete;
	}

}
