package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * UserQuizLikesEntity generated by hbm2java
 */
public class UserQuizLikesEntity implements java.io.Serializable {

	
	private static final long serialVersionUID = -7764698214631748355L;
	
	private UserQuizLikesEntityId id;

	public UserQuizLikesEntity() {
	}

	public UserQuizLikesEntity(UserQuizLikesEntityId id) {
		this.id = id;
	}

	public UserQuizLikesEntityId getId() {
		return this.id;
	}

	public void setId(UserQuizLikesEntityId id) {
		this.id = id;
	}

}
