package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 10:39:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRolesEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLES", catalog = "qme")
public class UserRolesEntity implements java.io.Serializable {

	private static final long serialVersionUID = 8593806823811122424L;
	
	private Long userRoleId;
	private Long userId;
	private Integer roleId;

	public UserRolesEntity() {
	}

	public UserRolesEntity(Long userId, Integer roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ROLE_ID", unique = true, nullable = false)
	public Long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Long userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "USER_ID", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
