package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

/**
 * UserQuestionLikesEntity generated by hbm2java
 */
public class UserQuestionLikesEntity implements java.io.Serializable {

	private static final long serialVersionUID = -5649195723277241965L;
	
	private UserQuestionLikesEntityId id;

	public UserQuestionLikesEntity() {
	}

	public UserQuestionLikesEntity(UserQuestionLikesEntityId id) {
		this.id = id;
	}

	public UserQuestionLikesEntityId getId() {
		return this.id;
	}

	public void setId(UserQuestionLikesEntityId id) {
		this.id = id;
	}

}
