/**
 * Name      : com.malcolm.qme.springdata.entity.UserQuizGameEntity.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserQuizGame Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserQuizGameEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_QUIZ_GAME", catalog = "qme")
public class UserQuizGameEntity implements java.io.Serializable {

	private static final long serialVersionUID = 8311601912412592958L;
	
	private UserQuizGameId id;
	private Date startDate;
	private Date endDate;
	private int userScore;

	public UserQuizGameEntity() {
	}

	public UserQuizGameEntity(UserQuizGameId id, Date startDate, int userScore) {
		this.id = id;
		this.startDate = startDate;
		this.userScore = userScore;
	}

	public UserQuizGameEntity(UserQuizGameId id, Date startDate, Date endDate,
							  int userScore) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
		this.userScore = userScore;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "catId", column = @Column(name = "CAT_ID", nullable = false)),
			@AttributeOverride(name = "quizGameToken", column = @Column(name = "QUIZ_GAME_TOKEN", nullable = false)) })
	public UserQuizGameId getId() {
		return this.id;
	}

	public void setId(UserQuizGameId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "USER_SCORE", nullable = false)
	public int getUserScore() {
		return this.userScore;
	}

	public void setUserScore(int userScore) {
		this.userScore = userScore;
	}

}
