/**
 * Name      : com.malcolm.qme.springdata.entity.UserRoles.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserRoles Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLES", catalog = "qme")
public class UserRoles implements java.io.Serializable {

	private static final long serialVersionUID = -7434452455969941779L;
	
	private Integer userRoleId;
	private int userId;
	private int roleId;

	public UserRoles() {
	}

	public UserRoles(int userId, int roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ROLE_ID", unique = true, nullable = false)
	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

}
