package com.malcolm.qme.springdata.entity;

// Generated May 14, 2015 7:02:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserCategoryLikesEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_CATEGORY_LIKES", catalog = "qme")
public class UserCategoryLikesEntity implements java.io.Serializable {

	
	private static final long serialVersionUID = 3588585992432983653L;
	
	private UserCategoryLikesEntityId id;

	public UserCategoryLikesEntity() {
	}

	public UserCategoryLikesEntity(UserCategoryLikesEntityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "catId", column = @Column(name = "CAT_ID", nullable = false)) })
	public UserCategoryLikesEntityId getId() {
		return this.id;
	}

	public void setId(UserCategoryLikesEntityId id) {
		this.id = id;
	}

}
