/**
 * Name      : com.malcolm.qme.springdata.entity.UserEntity.java
 * Date      : 5/3/15
 * Developer : Ma
 * lcolm
 * Purpose   : User Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserEntity generated by hbm2java
 */
@Entity
@Table(name = "USER", catalog = "qme", uniqueConstraints = @UniqueConstraint(columnNames = "USER_NAME"))
public class UserEntity implements java.io.Serializable {

	private static final long serialVersionUID = -1695545475168328036L;
	
	private Integer userId;
	private String userName;
	private String userFirstName;
	private String userLastName;
	private String userEmail;
	private String userPasscode;
	private Date userRegisteredDate;
	private Date userUpdatedDate;
	private Integer updateUser;

	public UserEntity() {
	}

	public UserEntity(String userName, String userFirstName, String userLastName,
					  String userEmail, String userPasscode, Date userRegisteredDate,
					  Date userUpdatedDate) {
		this.userName = userName;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmail = userEmail;
		this.userPasscode = userPasscode;
		this.userRegisteredDate = userRegisteredDate;
		this.userUpdatedDate = userUpdatedDate;
	}

	public UserEntity(String userName, String userFirstName, String userLastName,
					  String userEmail, String userPasscode, Date userRegisteredDate,
					  Date userUpdatedDate, Integer updateUser) {
		this.userName = userName;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmail = userEmail;
		this.userPasscode = userPasscode;
		this.userRegisteredDate = userRegisteredDate;
		this.userUpdatedDate = userUpdatedDate;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", unique = true, nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_FIRST_NAME", nullable = false, length = 128)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "USER_LAST_NAME", nullable = false, length = 128)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	@Column(name = "USER_EMAIL", nullable = false, length = 128)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "USER_PASSCODE", nullable = false, length = 512)
	public String getUserPasscode() {
		return this.userPasscode;
	}

	public void setUserPasscode(String userPasscode) {
		this.userPasscode = userPasscode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USER_REGISTERED_DATE", nullable = false, length = 19)
	public Date getUserRegisteredDate() {
		return this.userRegisteredDate;
	}

	public void setUserRegisteredDate(Date userRegisteredDate) {
		this.userRegisteredDate = userRegisteredDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USER_UPDATED_DATE", nullable = false, length = 19)
	public Date getUserUpdatedDate() {
		return this.userUpdatedDate;
	}

	public void setUserUpdatedDate(Date userUpdatedDate) {
		this.userUpdatedDate = userUpdatedDate;
	}

	@Column(name = "UPDATE_USER")
	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

}
