package com.malcolm.qme.springdata.entity;

// Generated May 4, 2015 9:22:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UserQuizGameEntity generated by hbm2java
 */
public class UserQuizGameEntity implements java.io.Serializable {

	
	private static final long serialVersionUID = 6369583277714554743L;
	
	private UserQuizGameEntityId id;
	private Date startDate;
	private Date endDate;
	private Integer userScore;

	public UserQuizGameEntity() {
	}

	public UserQuizGameEntity(UserQuizGameEntityId id, Date startDate,
			Integer userScore) {
		this.id = id;
		this.startDate = startDate;
		this.userScore = userScore;
	}

	public UserQuizGameEntity(UserQuizGameEntityId id, Date startDate,
			Date endDate, Integer userScore) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
		this.userScore = userScore;
	}

	public UserQuizGameEntityId getId() {
		return this.id;
	}

	public void setId(UserQuizGameEntityId id) {
		this.id = id;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getUserScore() {
		return this.userScore;
	}

	public void setUserScore(Integer userScore) {
		this.userScore = userScore;
	}

}
