/**
 * Name      : com.malcolm.qme.springdata.entity.UserQuizGameId.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserQuizGameId Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1

package com.malcolm.qme.springdata.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserQuizGameId generated by hbm2java
 */
@Embeddable
public class UserQuizGameId implements java.io.Serializable {

	private static final long serialVersionUID = -2390605997387295823L;
	
	private int userId;
	private int catId;
	private long quizGameToken;

	public UserQuizGameId() {
	}

	public UserQuizGameId(int userId, int catId, long quizGameToken) {
		this.userId = userId;
		this.catId = catId;
		this.quizGameToken = quizGameToken;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Column(name = "QUIZ_GAME_TOKEN", nullable = false)
	public long getQuizGameToken() {
		return this.quizGameToken;
	}

	public void setQuizGameToken(long quizGameToken) {
		this.quizGameToken = quizGameToken;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserQuizGameId))
			return false;
		UserQuizGameId castOther = (UserQuizGameId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getCatId() == castOther.getCatId())
				&& (this.getQuizGameToken() == castOther.getQuizGameToken());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getCatId();
		result = 37 * result + (int) this.getQuizGameToken();
		return result;
	}

}
