/**
 * Name      : com.malcolm.qme.springdata.entity.UserCategoryLikesId.java
 * Date      : 5/3/15
 * Developer : Malcolm
 * Purpose   : UserCategoryLikesId Entity Class
 */
// Generated May 3, 2015 6:11:19 PM by Hibernate Tools 4.3.1
package com.malcolm.qme.springdata.entity;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserCategoryLikesId generated by hbm2java
 */
@Embeddable
public class UserCategoryLikesId implements java.io.Serializable {

	private static final long serialVersionUID = -8188059515998484477L;
	
	private int userId;
	private int catId;

	public UserCategoryLikesId() {
	}

	public UserCategoryLikesId(int userId, int catId) {
		this.userId = userId;
		this.catId = catId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "CAT_ID", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserCategoryLikesId))
			return false;
		UserCategoryLikesId castOther = (UserCategoryLikesId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getCatId() == castOther.getCatId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getCatId();
		return result;
	}

}
