name: qme
version: 1.0.0
dependencies:
  bootstrap: ^3.3.4
  angular: "^1.1.2"
  web_components: "^0.12.0+2"
  browser:  "^0.10.0+2"
dev_dependencies:
  dartmocks: "^0.5.2+1"
  guinness: "^0.1.17"
transformers:
- angular:
    html_files:
        - lib/component/qme_header.html
        - lib/component/qme_error.html
        - lib/component/qme_main.html
        - lib/component/qme_register.html
        - lib/component/qme_forgotpassword.html