name: qme
version: 1.0.0
dependencies:
  bootstrap: ^3.3.4
  angular: "^1.1.2"
  web_components: "^0.12.0+2"
  browser:  "^0.10.0+2"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular