name: qme
version: 1.0.0
dependencies:
  bootstrap: ^3.3.4
  angular: "1.1.0"
  web_components: "0.10.1"
  browser: any
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    html_files:
      - lib/component/qme_header.html      
      - lib/component/qme_error.html
      - lib/component/qme_main.html