/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Malcolm' at '5/1/15 2:23 PM' with Gradle 2.3
 *
 * @author Malcolm, @date 5/1/15 2:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
